// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yezmonjxnhraczixxlfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inllem1vbmp4bmhyYWN6aXh4bGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTEyMjYsImV4cCI6MjA2MDk2NzIyNn0.KN7C5rUluZP2Fks7kRIy5-k91l5k0wm7l3KmHZLOC2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);